name: Update Supported Chains

on:
  workflow_dispatch:  # Allow manual triggering via GitHub UI
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight UTC

jobs:
  update-supported-chains:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout docs repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Clone docs-data-updater repository
        uses: actions/checkout@v4
        with:
          repository: pimlicolabs/docs-data-updater
          token: ${{ secrets.GH_PAT }}
          path: docs-data-updater
      
      - name: Configure npm for private packages
        working-directory: docs-data-updater
        run: |
          echo "@pimlicolabs:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      
      - name: Install dependencies in docs-data-updater
        working-directory: docs-data-updater
        run: pnpm install
      
      - name: Build docs-data-updater
        working-directory: docs-data-updater
        run: pnpm build
      
      - name: Create .env file with database credentials
        working-directory: docs-data-updater
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
      
      - name: Generate supported chains data
        working-directory: docs-data-updater
        run: pnpm generate:supported-chains > ../data/supported-chains.json
      
      - name: Check for changes
        id: check_changes
        run: |
          git add data/supported-chains.json
          if git diff --staged --quiet; then
            echo "No changes detected in supported-chains.json"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in supported-chains.json"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update supported chains data [automated]"
          title: "Update supported chains data - ${{ steps.date.outputs.date }}"
          body: |
            This PR updates the supported chains data from the Pimlico database.
            
            - Updated on: ${{ steps.date.outputs.date }}
            - Automated update via GitHub Actions
          branch: update-supported-chains-${{ steps.date.outputs.date }}
          base: main
          delete-branch: true
          labels: |
            automated
            data-update
